server.port=8080
spring.application.name=gateway-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.default-filters[0]=JwtGatewayFilter

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=empleado-service
spring.cloud.gateway.routes[1].uri=lb://empleado-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/empleados/**

spring.cloud.gateway.routes[2].id=asistencia-service
spring.cloud.gateway.routes[2].uri=lb://asistencia-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/asistencias/**

spring.cloud.gateway.routes[3].id=tarea-service
spring.cloud.gateway.routes[3].uri=lb://tarea-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/tareas/**

spring.cloud.gateway.routes[4].id=notification-service
spring.cloud.gateway.routes[4].uri=lb://notification-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/notificaciones/**

spring.cloud.gateway.routes[5].id=notification-ws
spring.cloud.gateway.routes[5].uri=lb:ws://notification-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/ws/**
